#!/bin/bash
 
RED='\033[1;31m'
NC='\033[0m'
LIGHT_RED='\e[1;91m'
LIGHT_CYNE='\e[1;96m'
ENDCOLOR="\e[0m"
REGEX_ISSUE_ID="^(\[NPE-[1-9][0-9]*\]\:\ \w.*)"
ISSUE_ID_IN_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_ISSUE_ID")
 
if [[ -z "$ISSUE_ID_IN_COMMIT" ]]; then
   BRANCH_NAME=$(git symbolic-ref --short HEAD)
   ISSUE_ID=$(echo "[$BRANCH_NAME]:" | grep -o -E "$REGEX_ISSUE_ID")
 
   if [[ -z "$ISSUE_ID" ]]; then
       echo -e 
       echo -e "${RED} -------- ERROR [commit-msg-hook][ABORTING COMMIT] -------- ${ENDCOLOR}"  
       echo -e "${LIGHT_RED}[REASON]${ENDCOLOR}: Please provide proper commit message with ticket ID ([Ticket ID]: Commit Message)."
       echo -e "${RED} --------------------------- END -------------------------- ${ENDCOLOR}"  
       echo -e 
       exit 1
   fi
 
#    echo "$ISSUE_ID $(cat "$1")" > "$1"
fi
